SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{A1B2C3D4E5F60001}" {
  Name "Insurgency Reforged"
  Description "Insurgency Reforged Configuration"
  Icon "{6DA0E6198CDDE51A}Assets/UI/ins_icon.edds"
 }
 m_iPriority 1
 m_bIsGlobalAttributeCategory 1
}