SCR_GameOverScreenConfig {
 m_aGameOverScreens {
  SCR_FactionVictoryGameOverScreenInfo "{56D6AA9BDC7D83DE}" {
   m_OptionalParams SCR_BaseGameOverScreenInfoOptional "{568E79DB9224CAB6}" {
    m_sTitle "Victory!"
    m_sSubtitle "All enemy caches were destroyed."
    m_sDebriefing "Against the odds, friendly forces pushed through enemy held territory and destroyed every weapons cache on the island. Their ranks are in chaos."
   }
  }
 }
}