SCR_MissionHeaderCombatOps {
 World "{015E9BFEEF4C7A07}Worlds/InsEden.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "Insurgency Reforged"
 m_sAuthor "borked.gb"
 m_sDescription "Clear towns, gather intel and destory enemy caches."
 m_sDetails " A Reforger reimagining of the classic Arma 2 Insurgency scenario."
 m_sIcon "{44B225C000F45520}Assets/Images/INS_REF_0.edds"
 m_sLoadingScreen "{44B225C000F45520}Assets/Images/INS_REF_0.edds"
 m_sGameMode "INS"
 m_iPlayerCount 32
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 6
 m_iStartingMinutes 30
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_iMapMarkerLimitPerPlayer 21
 m_aFactionLimits {
  SCR_FactionLimit "{6978F075A50C2F5F}" {
   m_sFactionKey "USSR"
   m_iFactionLimit 8
  }
 }
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B55DA84}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B2725C3}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41BE3799A}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B944989}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A40B5073D5}" {
   m_eTypeOfTask DEFEND
  }
 }
}